var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var schema = new Schema({
    eventName: {type:String, required:[true, 'Event Name is required']},
    eventLogo: {type:String},
    fromDate: {type: Date, required:[true, 'From Date is required'] },
    toDate: {type: Date, required:[true, 'To Date is required'] },


    uniqueId_label: {type:String, default:'Unique ID'},
    uniqueId_isMandatory: {type:Boolean, default:false}, 
    uniqueId_showInSearch: {type:Boolean, default:false},
    uniqueId_includeInSearch: {type:Boolean, default:false},
    uniqueId_showInRegister: {type:Boolean, default:false},
    uniqueId_showInPrint: {type:Boolean, default:false},
    uniqueId_columnInExcel: {type:String, default:'A'},

    barcode_label: {type:String, default:'Barcode'},
    barcode_isMandatory: {type:Boolean}, 
    barcode_showInSearch: {type:Boolean},
    barcode_includeInSearch: {type:Boolean},
    barcode_showInRegister: {type:Boolean},
    barcode_showInPrint: {type:Boolean},
    barcode_columnInExcel: {type:String, default:'B'},

    sno_label: {type:String, default:'SNo'},
    sno_isMandatory: {type:Boolean}, 
    sno_showInSearch: {type:Boolean},
    sno_includeInSearch: {type:Boolean},
    sno_showInRegister: {type:Boolean},
    sno_showInPrint: {type:Boolean},
    sno_columnInExcel: {type:String, default:'C'},

    title_label: {type:String, default:'Title'},
    title_isMandatory: {type:Boolean}, 
    title_showInSearch: {type:Boolean},
    title_includeInSearch: {type:Boolean},
    title_showInRegister: {type:Boolean},
    title_showInPrint: {type:Boolean},
    title_columnInExcel: {type:String, default:'D'},

    firstName_label: {type:String, default:'First Name'},
    firstName_isMandatory: {type:Boolean}, 
    firstName_showInSearch: {type:Boolean},
    firstName_includeInSearch: {type:Boolean},
    firstName_showInRegister: {type:Boolean},
    firstName_showInPrint: {type:Boolean},
    firstName_columnInExcel: {type:String, default:'E'},

    middleName_label: {type:String, default:'Middle Name'},
    middleName_isMandatory: {type:Boolean}, 
    middleName_showInSearch: {type:Boolean},
    middleName_includeInSearch: {type:Boolean},
    middleName_showInRegister: {type:Boolean},
    middleName_showInPrint: {type:Boolean},
    middleName_columnInExcel: {type:String, default:'F'},

    lastName_label: {type:String, default:'Last Name'},
    lastName_isMandatory: {type:Boolean}, 
    lastName_showInSearch: {type:Boolean},
    lastName_includeInSearch: {type:Boolean},
    lastName_showInRegister: {type:Boolean},
    lastName_showInPrint: {type:Boolean},
    lastName_columnInExcel: {type:String, default:'G'},

    fullName_label: {type:String, default:'Full Name'},
    fullName_isMandatory: {type:Boolean}, 
    fullName_showInSearch: {type:Boolean},
    fullName_includeInSearch: {type:Boolean},
    fullName_showInRegister: {type:Boolean},
    fullName_showInPrint: {type:Boolean},
    fullName_columnInExcel: {type:String, default:'H'},

    jobTitle_label: {type:String, default:'Job Title'},
    jobTitle_isMandatory: {type:Boolean}, 
    jobTitle_showInSearch: {type:Boolean},
    jobTitle_includeInSearch: {type:Boolean},
    jobTitle_showInRegister: {type:Boolean},
    jobTitle_showInPrint: {type:Boolean},
    jobTitle_columnInExcel: {type:String, default:'I'},

    department_label: {type:String, default:'Department'},
    department_isMandatory: {type:Boolean}, 
    department_showInSearch: {type:Boolean},
    department_includeInSearch: {type:Boolean},
    department_showInRegister: {type:Boolean},
    department_showInPrint: {type:Boolean},
    department_columnInExcel: {type:String, default:'J'},

    companyName_label: {type:String, default:'Company Name'},
    companyName_isMandatory: {type:Boolean}, 
    companyName_showInSearch: {type:Boolean},
    companyName_includeInSearch: {type:Boolean},
    companyName_showInRegister: {type:Boolean},
    companyName_showInPrint: {type:Boolean},
    companyName_columnInExcel: {type:String, default:'K'},

    mobile1_label: {type:String, default:'Mobile 1'},
    mobile1_isMandatory: {type:Boolean}, 
    mobile1_showInSearch: {type:Boolean},
    mobile1_includeInSearch: {type:Boolean},
    mobile1_showInRegister: {type:Boolean},
    mobile1_showInPrint: {type:Boolean},
    mobile1_columnInExcel: {type:String, default:'L'},

    mobile2_label: {type:String, default:'Mobile 2'},
    mobile2_isMandatory: {type:Boolean}, 
    mobile2_showInSearch: {type:Boolean},
    mobile2_includeInSearch: {type:Boolean},
    mobile2_showInRegister: {type:Boolean},
    mobile2_showInPrint: {type:Boolean},
    mobile2_columnInExcel: {type:String, default:'M'},

    tel1_label: {type:String, default:'Tel 1'},
    tel1_isMandatory: {type:Boolean}, 
    tel1_showInSearch: {type:Boolean},
    tel1_includeInSearch: {type:Boolean},
    tel1_showInRegister: {type:Boolean},
    tel1_showInPrint: {type:Boolean},
    tel1_columnInExcel: {type:String, default:'N'},

    tel2_label: {type:String, default:'Tel 2'},
    tel2_isMandatory: {type:Boolean}, 
    tel2_showInSearch: {type:Boolean},
    tel2_includeInSearch: {type:Boolean},
    tel2_showInRegister: {type:Boolean},
    tel2_showInPrint: {type:Boolean},
    tel2_columnInExcel: {type:String, default:'O'},

    fax_label: {type:String, default:'Fax'},
    fax_isMandatory: {type:Boolean}, 
    fax_showInSearch: {type:Boolean},
    fax_includeInSearch: {type:Boolean},
    fax_showInRegister: {type:Boolean},
    fax_showInPrint: {type:Boolean},
    fax_columnInExcel: {type:String, default:'P'},

    email_label: {type:String, default:'Email'},
    email_isMandatory: {type:Boolean}, 
    email_showInSearch: {type:Boolean},
    email_includeInSearch: {type:Boolean},
    email_showInRegister: {type:Boolean},
    email_showInPrint: {type:Boolean},
    email_columnInExcel: {type:String, default:'Q'},

    website_label: {type:String, default:'Website'},
    website_isMandatory: {type:Boolean}, 
    website_showInSearch: {type:Boolean},
    website_includeInSearch: {type:Boolean},
    website_showInRegister: {type:Boolean},
    website_showInPrint: {type:Boolean},
    website_columnInExcel: {type:String, default:'R'},

    address1_label: {type:String, default:'Address 1'},
    address1_isMandatory: {type:Boolean}, 
    address1_showInSearch: {type:Boolean},
    address1_includeInSearch: {type:Boolean},
    address1_showInRegister: {type:Boolean},
    address1_showInPrint: {type:Boolean},
    address1_columnInExcel: {type:String, default:'S'},

    address2_label: {type:String, default:'Address 2'},
    address2_isMandatory: {type:Boolean}, 
    address2_showInSearch: {type:Boolean},
    address2_includeInSearch: {type:Boolean},
    address2_showInRegister: {type:Boolean},
    address2_showInPrint: {type:Boolean},
    address2_columnInExcel: {type:String, default:'T'},
  
    city_label: {type:String, default:'City'},
    city_isMandatory: {type:Boolean}, 
    city_showInSearch: {type:Boolean},
    city_includeInSearch: {type:Boolean},
    city_showInRegister: {type:Boolean},
    city_showInPrint: {type:Boolean},
    city_columnInExcel: {type:String, default:'U'},

    country_label: {type:String, default:'Country'},
    country_isMandatory: {type:Boolean}, 
    country_showInSearch: {type:Boolean},
    country_includeInSearch: {type:Boolean},
    country_showInRegister: {type:Boolean},
    country_showInPrint: {type:Boolean},
    country_columnInExcel: {type:String, default:'V'},

    poBox_label: {type:String, default:'P.O.Box'},
    poBox_isMandatory: {type:Boolean}, 
    poBox_showInSearch: {type:Boolean},
    poBox_includeInSearch: {type:Boolean},
    poBox_showInRegister: {type:Boolean},
    poBox_showInPrint: {type:Boolean},
    poBox_columnInExcel: {type:String, default:'W'},

    postalCode_label: {type:String, default:'Postal Code'},
    postalCode_isMandatory: {type:Boolean}, 
    postalCode_showInSearch: {type:Boolean},
    postalCode_includeInSearch: {type:Boolean},
    postalCode_showInRegister: {type:Boolean},
    postalCode_showInPrint: {type:Boolean},
    postalCode_columnInExcel: {type:String, default:'X'},

    badgeCategory_label: {type:String, default:'Badge Category'},
    badgeCategory_isMandatory: {type:Boolean}, 
    badgeCategory_showInSearch: {type:Boolean},
    badgeCategory_includeInSearch: {type:Boolean},
    badgeCategory_showInRegister: {type:Boolean},
    badgeCategory_showInPrint: {type:Boolean},
    badgeCategory_columnInExcel: {type:String, default:'Y'},

    regType_label: {type:String, default:'Reg Type'},
    regType_isMandatory: {type:Boolean}, 
    regType_showInSearch: {type:Boolean},
    regType_includeInSearch: {type:Boolean},
    regType_showInRegister: {type:Boolean},
    regType_showInPrint: {type:Boolean},
    regType_columnInExcel: {type:String, default:'Z'},

    regDate_label: {type:String, default:'Reg Date'},
    regDate_isMandatory: {type:Boolean}, 
    regDate_showInSearch: {type:Boolean},
    regDate_includeInSearch: {type:Boolean},
    regDate_showInRegister: {type:Boolean},
    regDate_showInPrint: {type:Boolean},
    regDate_columnInExcel: {type:String, default:'AA'},
 
    badgePrintDate_label: {type:String, default:'Badge Print Date'},
    badgePrintDate_isMandatory: {type:Boolean}, 
    badgePrintDate_showInSearch: {type:Boolean},
    badgePrintDate_includeInSearch: {type:Boolean},
    badgePrintDate_showInRegister: {type:Boolean},
    badgePrintDate_showInPrint: {type:Boolean},
    badgePrintDate_columnInExcel: {type:String, default:'AB'},

    modifiedDate_label: {type:String, default:'Modified Date'},
    modifiedDate_isMandatory: {type:Boolean}, 
    modifiedDate_showInSearch: {type:Boolean},
    modifiedDate_includeInSearch: {type:Boolean},
    modifiedDate_showInRegister: {type:Boolean},
    modifiedDate_showInPrint: {type:Boolean},
    modifiedDate_columnInExcel: {type:String, default:'AC'},

    statusFlag_label: {type:String, default:'Status Flag'},
    statusFlag_isMandatory: {type:Boolean}, 
    statusFlag_showInSearch: {type:Boolean},
    statusFlag_includeInSearch: {type:Boolean},
    statusFlag_showInRegister: {type:Boolean},
    statusFlag_showInPrint: {type:Boolean},
    statusFlag_columnInExcel: {type:String, default:'AD'},

    backoffice_label: {type:String, default:'Backoffice'},
    backoffice_isMandatory: {type:Boolean}, 
    backoffice_showInSearch: {type:Boolean},
    backoffice_includeInSearch: {type:Boolean},
    backoffice_showInRegister: {type:Boolean},
    backoffice_showInPrint: {type:Boolean},
    backoffice_columnInExcel: {type:String, default:'AE'},

    comment1_label: {type:String, default:'Comment 1'},
    comment1_isMandatory: {type:Boolean}, 
    comment1_showInSearch: {type:Boolean},
    comment1_includeInSearch: {type:Boolean},
    comment1_showInRegister: {type:Boolean},
    comment1_showInPrint: {type:Boolean},
    comment1_columnInExcel: {type:String, default:'AF'},

    comment2_label: {type:String, default:'Comment 2'},
    comment2_isMandatory: {type:Boolean}, 
    comment2_showInSearch: {type:Boolean},
    comment2_includeInSearch: {type:Boolean},
    comment2_showInRegister: {type:Boolean},
    comment2_showInPrint: {type:Boolean},
    comment2_columnInExcel: {type:String, default:'AG'},
  
    comment3_label: {type:String, default:'Comment 3'},
    comment3_isMandatory: {type:Boolean}, 
    comment3_showInSearch: {type:Boolean},
    comment3_includeInSearch: {type:Boolean},
    comment3_showInRegister: {type:Boolean},
    comment3_showInPrint: {type:Boolean},
    comment3_columnInExcel: {type:String, default:'AH'},

    comment4_label: {type:String, default:'Comment 4'},
    comment4_isMandatory: {type:Boolean}, 
    comment4_showInSearch: {type:Boolean},
    comment4_includeInSearch: {type:Boolean},
    comment4_showInRegister: {type:Boolean},
    comment4_showInPrint: {type:Boolean},
    comment4_columnInExcel: {type:String, default:'AI'},

    comment5_label: {type:String, default:'Comment 5'},
    comment5_isMandatory: {type:Boolean}, 
    comment5_showInSearch: {type:Boolean},
    comment5_includeInSearch: {type:Boolean},
    comment5_showInRegister: {type:Boolean},
    comment5_showInPrint: {type:Boolean},
    comment5_columnInExcel: {type:String, default:'AJ'},

    comment6_label: {type:String, default:'Comment 6'},
    comment6_isMandatory: {type:Boolean}, 
    comment6_showInSearch: {type:Boolean},
    comment6_includeInSearch: {type:Boolean},
    comment6_showInRegister: {type:Boolean},
    comment6_showInPrint: {type:Boolean},
    comment6_columnInExcel: {type:String, default:'AK'},

    comment7_label: {type:String, default:'Comment 7'},
    comment7_isMandatory: {type:Boolean}, 
    comment7_showInSearch: {type:Boolean},
    comment7_includeInSearch: {type:Boolean},
    comment7_showInRegister: {type:Boolean},
    comment7_showInPrint: {type:Boolean},
    comment7_columnInExcel: {type:String, default:'AL'},

    comment8_label: {type:String, default:'Comment 8'},
    comment8_isMandatory: {type:Boolean}, 
    comment8_showInSearch: {type:Boolean},
    comment8_includeInSearch: {type:Boolean},
    comment8_showInRegister: {type:Boolean},
    comment8_showInPrint: {type:Boolean},
    comment8_columnInExcel: {type:String, default:'AM'},

    comment9_label: {type:String, default:'Comment 9'},
    comment9_isMandatory: {type:Boolean}, 
    comment9_showInSearch: {type:Boolean},
    comment9_includeInSearch: {type:Boolean},
    comment9_showInRegister: {type:Boolean},
    comment9_showInPrint: {type:Boolean},
    comment9_columnInExcel: {type:String, default:'AN'},

    comment10_label: {type:String, default:'Comment 10'},
    comment10_isMandatory: {type:Boolean}, 
    comment10_showInSearch: {type:Boolean},
    comment10_includeInSearch: {type:Boolean},
    comment10_showInRegister: {type:Boolean},
    comment10_showInPrint: {type:Boolean},
    comment10_columnInExcel: {type:String, default:'AO'},


});

module.exports = mongoose.model('Event', schema);